name: Build a one-file executable

on:
  push:
    tags:
      - "**"

jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout the GTModTools
        uses: actions/checkout@v2
        with:
          repository: CookiePLMonster/GTModTools
          path: gttools
      - name: Checkout PyInstaller
        uses: actions/checkout@v2
        with:
          repository: pyinstaller/pyinstaller
          path: custom_pyinstaller
          ref: v4.9
      - name: Setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Compile pyinstaller from source
        run: cd custom_pyinstaller/bootloader && python ./waf all --target-arch=64bit
      - name: Install pyinstaller
        run: pip install wheel && cd custom_pyinstaller && python setup.py install
      - name: Package into a one file executable
        run: pyinstaller -F setup.py -n gt2_discs_combiner
      - name: Copy resources into /dist
        run: foreach ($directory in ("menu_entries", "tools", "vol_replacements")) { Xcopy /E /I $directory dist\$directory }
      - name: Package the build into a zip file
        run: tar -c -f gt2_discs_combiner.zip -C dist *
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gt2_discs_combiner.zip
